/**
 * Registers a running checkout with the shared Traefik proxy, so it answers on its own hostname.
 *
 * One routes directory now serves every project on the machine, so the file and router names have
 * to be unique across projects, not just across a project's worktrees. `identity.slug` already
 * carries the repo name for exactly that reason.
 *
 * How the routing works, and why it is a file rather than a container label: the dev server is a
 * HOST process, not a container, so Traefik's Docker provider cannot discover it. Its file provider
 * watches a directory and hot-reloads, so each running checkout drops one generated file in and
 * removes it on exit. Nothing is hand-maintained and nothing is shared between checkouts.
 *
 * The route always points at `host.docker.internal`, which the infra stack maps to the host gateway
 * so it resolves on Linux/WSL as well as Docker Desktop's own platforms.
 *
 * Counterpart: `infra/compose.yml` (the proxy itself) and `infra/traefik.yml` (which names the
 * directory written here). Changing the directory means changing both.
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'

/** One file per checkout, named from the slug so a stale file is obvious and safe to delete. */
export function routeFilePath(config, identity) {
  return path.join(config.routesDir, `${identity.slug}.yml`)
}

/**
 * Writes this checkout's route. Idempotent, and cheap enough to do on every start.
 *
 * Traefik watches the directory, so the route is live within a moment of the write; there is no
 * reload to trigger and no proxy restart, which is what keeps a second checkout starting up from
 * interrupting the first one's session.
 */
export function writeRoute(config, identity, port) {
  mkdirSync(config.routesDir, { recursive: true })
  const name = identity.slug
  const contents = `# Generated by scripts/dev/host-mode. Rewritten on every \`npm run dev\`, removed on exit.
http:
  routers:
    ${name}:
      rule: "Host(\`${identity.hostname}\`)"
      service: ${name}
      entryPoints:
        - web
  services:
    ${name}:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:${port}"
`
  writeFileSync(routeFilePath(config, identity), contents, 'utf8')
  return routeFilePath(config, identity)
}

/**
 * Removes this checkout's route.
 *
 * Best-effort: a leftover file routes to a port nobody is listening on, which Traefik reports as a
 * bad gateway rather than misrouting to another checkout, so failing to clean up is never dangerous
 * enough to interrupt shutdown.
 */
export function removeRoute(config, identity) {
  try {
    rmSync(routeFilePath(config, identity), { force: true })
  } catch {
    // See above: a stale route cannot misroute, so there is nothing worth reporting here.
  }
}
